{% set name = "nfoursid" %}
{% set version = "1.0.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 9dc20edeaf0203ebbff9ef6ccad6ff125d9ab73d6c1ab48934fdb24b37f5f097

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - matplotlib-base >=3.3
    - numpy >=1.19
    - pandas >=1.1

test:
  imports:
    - nfoursid
    - nfoursid.tests
  requires:
    - pip
  commands:
    - python -m unittest discover -v nfoursid.tests

about:
  home: https://github.com/spmvg/nfoursid
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "Implementation of N4SID, Kalman filtering and state-space models"
  doc_url: https://nfoursid.readthedocs.io/en/latest/
  dev_url: https://github.com/spmvg/nfoursid

extra:
  recipe-maintainers:
    - spmvg
